package com.mazpiss.skripsi.ui.theme

import androidx.compose.ui.graphics.Color

// Material You — Shorof Design System (Light)
val Primary = Color(0xFF006579)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF008098)
val OnPrimaryContainer = Color(0xFFF9FDFF)
val PrimaryFixed = Color(0xFFB1ECFF)
val PrimaryFixedDim = Color(0xFF6ED4F1)
val OnPrimaryFixed = Color(0xFF001F27)
val OnPrimaryFixedVariant = Color(0xFF004E5E)
val InversePrimary = Color(0xFF6ED4F1)

val Secondary = Color(0xFF576061)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFD8E1E2)
val OnSecondaryContainer = Color(0xFF5B6465)
val SecondaryFixed = Color(0xFFDBE4E5)
val SecondaryFixedDim = Color(0xFFBFC8C9)
val OnSecondaryFixed = Color(0xFF151D1E)
val OnSecondaryFixedVariant = Color(0xFF404849)

val Tertiary = Color(0xFF795600)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF986D00)
val OnTertiaryContainer = Color(0xFFFFFBFF)
val TertiaryFixed = Color(0xFFFFDEA8)
val TertiaryFixedDim = Color(0xFFFFBA20)
val OnTertiaryFixed = Color(0xFF271900)
val OnTertiaryFixedVariant = Color(0xFF5E4200)

val ErrorColor = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)

val Background = Color(0xFFF8F9FA)
val OnBackground = Color(0xFF191C1D)
val Surface = Color(0xFFF8F9FA)
val OnSurface = Color(0xFF191C1D)
val SurfaceVariant = Color(0xFFE1E3E4)
val OnSurfaceVariant = Color(0xFF3E484C)
val SurfaceBright = Color(0xFFF8F9FA)
val SurfaceDim = Color(0xFFD8DADB)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF2F4F5)
val SurfaceContainer = Color(0xFFECEEEF)
val SurfaceContainerHigh = Color(0xFFE7E8E9)
val SurfaceContainerHighest = Color(0xFFE1E3E4)
val SurfaceTint = Color(0xFF00677C)

val Outline = Color(0xFF6E797D)
val OutlineVariant = Color(0xFFBDC8CD)
val InverseSurface = Color(0xFF2E3132)
val InverseOnSurface = Color(0xFFEFF1F2)

// Dark theme — derived inversions
val DarkPrimary = Color(0xFF6ED4F1)
val DarkOnPrimary = Color(0xFF001F27)
val DarkPrimaryContainer = Color(0xFF004E5E)
val DarkOnPrimaryContainer = Color(0xFFB1ECFF)
val DarkSecondary = Color(0xFFBFC8C9)
val DarkOnSecondary = Color(0xFF2B3334)
val DarkSecondaryContainer = Color(0xFF404849)
val DarkOnSecondaryContainer = Color(0xFFDBE4E5)
val DarkTertiary = Color(0xFFFFBA20)
val DarkOnTertiary = Color(0xFF402D00)
val DarkTertiaryContainer = Color(0xFF5E4200)
val DarkOnTertiaryContainer = Color(0xFFFFDEA8)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF191C1D)
val DarkOnBackground = Color(0xFFE1E3E4)
val DarkSurface = Color(0xFF191C1D)
val DarkOnSurface = Color(0xFFE1E3E4)
val DarkSurfaceVariant = Color(0xFF3E484C)
val DarkOnSurfaceVariant = Color(0xFFBDC8CD)
val DarkOutline = Color(0xFF889296)
val DarkOutlineVariant = Color(0xFF3E484C)
val DarkInverseSurface = Color(0xFFE1E3E4)
val DarkInverseOnSurface = Color(0xFF2E3132)
val DarkInversePrimary = Color(0xFF006579)
val DarkSurfaceContainerLowest = Color(0xFF0D1617)
val DarkSurfaceContainerLow = Color(0xFF191C1D)
val DarkSurfaceContainer = Color(0xFF1D2021)
val DarkSurfaceContainerHigh = Color(0xFF282B2C)
val DarkSurfaceContainerHighest = Color(0xFF333537)
